language: node_js
node_js:
  - "node"
install:
  - npm install
  - npm install surge
script:
  - npm run lint
deploy:
  provider: script
  project: ./build/
  skip_cleanup: true
  script:
    - npm run build && surge -d selfish-roof.surge.sh --token=$SURGE_TOKEN -p build
