language: node_js
node_js:
  - "node"
install:
  - npm install
  - npm install surge
script:
  - npm run lint
  - npm run deploy
deploy:
  provider: surge
  project: ./build/
  domain: selfish-roof.surge.sh
  skip_cleanup: true
